### PR TITLE
passes model specs, adds and configures database_cleaner, validates models

### PR DESCRIPTION
**Pull request by kylestengline**
Model Specs pass!

### CODE REVIEW

**Comment by appleJax** [comment]
Travis CI error:
```
An error occurred while loading ./spec/models/events_user_spec.rb.
Failure/Error: ActiveRecord::Migration.maintain_test_schema!
ActiveRecord::PendingMigrationError:
  Migrations are pending. To resolve this issue, run:
          bin/rails db:migrate RAILS_ENV=test
# ./spec/rails_helper.rb:28:in `<top (required)>'
# ./spec/models/events_user_spec.rb:1:in `<top (required)>'
```
Do we need to put `bin/rails db:migrate RAILS_ENV=test` into `.travis.yml`? Not sure why this error is just showing up now...

**Comment by kylestengline** [comment]
@appleJax I believe I fixed the issue. TravisCI shows as passing now.

**Comment by appleJax** [comment]
TravisCI Error: `RuntimeError: Unable to find a spec satisfying foreman (>= 0) in the set. Perhaps the lockfile is corrupted?`

Three observations:
- Foreman was removed because Webpacker 3.0 makes it unnecessary.
- Without foreman, the default address for the rails server is `localhost:3000`
- The Procfile in the root directory is unnecessary now that foreman is gone. I forgot to delete it

**Comment by appleJax** [comment]
@kylestengline foreman is still causing an issue with TravisCI. Can you delete it from the Gemfile and run `bundle`? Also, the README.md from upstream master is the correct one, you can copy it from there.

**Comment by kylestengline** [comment]
@appleJax Will do. Working on it now.

**Comment by kylestengline** [comment]
YES!!!

**Pull request merged**
