### PR TITLE
Ignore single-quote rule in hound config

### PR DESCRIPTION
**Pull request by appleJax**
First attempt, hopefully this works...

### CODE REVIEW

**Comment by appleJax** [comment]
On second thought, we should probably enforce consistency, so should we configure hound to complain about single quotes? Personally, I kinda like the convention of only using double quotes when you need escape characters or interpolation.

**Comment by gabrielbonner** [comment]
I second the 'default to single quotes and only use double quotes when necessary' convention @appleJax.

**Comment by appleJax** [comment]
@kylestengline do you have a preference? Should we outlaw single quotes, or always use single quotes unless we need interpolation or escape characters?

**Comment by kylestengline** [comment]
@applejax I think to use double quotes only when necessary is best. Default to single quotes is good for me.

**Pull request closed without merging**
