### PR TITLE
Style signout

### PR DESCRIPTION
**Pull request by appleJax**
Hides signout button, accessible by clicking on Username

### CODE REVIEW

**Comment by gabrielbonner** [comment]
Looks like you styled it expecting to put more buttons there in the future...?  I'd say merge at will.

screen shot 2017-09-15 at 7 43 03 am

**Comment by gabrielbonner** [comment]
@appleJax I added a fade in/out for kicks  :)

**Comment by appleJax** [comment]
@gabrielbonner nice! I fixed the vertical positioning and added a little slide down.

**Comment by gabrielbonner** [comment]
I'd say merge away @appleJax, looks good.   👍   I didn't change the hover color on the button because I think there's a chance we'll have to change the navbar dodgerblue color, it's not complementing the landing page image that I'm working on...

**Pull request merged**
